---
# vars file for openssh

_openssh_packages:
  default:
    - openssh-server
  Suse:
    - openssh

openssh_packages: "{{ _openssh_packages[ansible_os_family] | default(_openssh_packages['default']) }}"

openssh_key_types:
  - rsa
  - ecdsa
  - ed25519
